# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.7 on 2018-02-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.11.7 on 2017-12-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> 21bc2e0b6d254d6cc1c10df7bef94362fa727c6e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.IntegerField()),
                ('is_skipped', models.PositiveSmallIntegerField()),
                ('time_taken', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('ques_id', models.IntegerField(primary_key=True, serialize=False)),
=======
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.IntegerField()),
>>>>>>> 21bc2e0b6d254d6cc1c10df7bef94362fa727c6e
                ('statement', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
                ('op4', models.CharField(max_length=300)),
<<<<<<< HEAD
                ('ans', models.CharField(max_length=300)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('TCI', models.FloatField()),
                ('time', models.FloatField()),
                ('clusters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=10)),
                ('quiz_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
                ('badges', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('clusters', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizUserID', to='play.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subUser', to='play.subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ques_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansQuesID', to='play.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansQuiz', to='play.quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansSub', to='play.subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansUserID', to='play.user'),
        ),
=======
            ],
        ),
>>>>>>> 21bc2e0b6d254d6cc1c10df7bef94362fa727c6e
    ]
