# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='play.question'),
            preserve_default=False,
        ),
    ]
