# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_user_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionKey', to='play.question'),
        ),
    ]
